// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGGYMjN8iqg32fJXR9k1g0VeL4IVqIRw',
    appId: '1:243338442049:web:53cdebc43ed2e6f2b99dc0',
    messagingSenderId: '243338442049',
    projectId: 'fit-flow-466c1',
    authDomain: 'fit-flow-466c1.firebaseapp.com',
    storageBucket: 'fit-flow-466c1.firebasestorage.app',
    measurementId: 'G-4KQ82YTV9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJyhtDpuF91-0a0up9u9wyVgSwDRx1zg',
    appId: '1:243338442049:android:71d17071c479231fb99dc0',
    messagingSenderId: '243338442049',
    projectId: 'fit-flow-466c1',
    storageBucket: 'fit-flow-466c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOfxreiP6n86A7SeEFAf-2k7ClKiiAhM4',
    appId: '1:243338442049:ios:17d957ca0c1e4e93b99dc0',
    messagingSenderId: '243338442049',
    projectId: 'fit-flow-466c1',
    storageBucket: 'fit-flow-466c1.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOfxreiP6n86A7SeEFAf-2k7ClKiiAhM4',
    appId: '1:243338442049:ios:17d957ca0c1e4e93b99dc0',
    messagingSenderId: '243338442049',
    projectId: 'fit-flow-466c1',
    storageBucket: 'fit-flow-466c1.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtGGYMjN8iqg32fJXR9k1g0VeL4IVqIRw',
    appId: '1:243338442049:web:1978bae4ee02517db99dc0',
    messagingSenderId: '243338442049',
    projectId: 'fit-flow-466c1',
    authDomain: 'fit-flow-466c1.firebaseapp.com',
    storageBucket: 'fit-flow-466c1.firebasestorage.app',
    measurementId: 'G-B1BN9Y5KJ4',
  );
}
